use std::{collections::HashSet, str::FromStr};

use miette::{miette, Report, Result};
use rand::seq::IteratorRandom;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Palette {
	All,
	Common,
	Extended,
	Html,
	Beer,
	Stamps,
	Crayola,
	Resene,
	Colorsteel,
	RalClassic,
	RalF9,
	Munsell,
	Saccardo,
}

impl FromStr for Palette {
	type Err = Report;

	fn from_str(s: &str) -> Result<Self> {
		Ok(match s {
			"all" => Self::All,
			"common" => Self::Common,
			"extended" => Self::Extended,
			"html" => Self::Html,
			"beer" => Self::Beer,
			"stamps" => Self::Stamps,
			"crayola" => Self::Crayola,
			"resene" => Self::Resene,
			"colorsteel" => Self::Colorsteel,
			"ral-classic" => Self::RalClassic,
			"ral-f9" => Self::RalF9,
			"munsell" => Self::Munsell,
			"saccardo" => Self::Saccardo,
			_ => return Err(miette!("invalid colour palette")),
		})
	}
}

impl Palette {
	pub fn random(self) -> String {
		let set = match self {
			Palette::All => vec![
				&COMMON[..],
				&EXTENDED[..],
				&HTML[..],
				&BEER[..],
				&POSTAGE_STAMP[..],
				&CRAYOLA_STANDARD[..],
				&CRAYOLA_FLUORESCENT[..],
				&CRAYOLA_METALLIC[..],
				&CRAYOLA_SWIRL[..],
				&CRAYOLA_GEMS[..],
				&RESENE[..],
				&COLORSTEEL[..],
				&RAL_CLASSIC[..],
				&RAL_F9[..],
				&MUNSELL[..],
				&SACCARDO[..],
			],
			Palette::Common => vec![&COMMON[..]],
			Palette::Extended => vec![&EXTENDED[..]],
			Palette::Html => vec![&HTML[..]],
			Palette::Beer => vec![&BEER[..]],
			Palette::Stamps => vec![&POSTAGE_STAMP[..]],
			Palette::Crayola => vec![
				&CRAYOLA_STANDARD[..],
				&CRAYOLA_FLUORESCENT[..],
				&CRAYOLA_METALLIC[..],
				&CRAYOLA_SWIRL[..],
				&CRAYOLA_GEMS[..],
			],
			Palette::Resene => vec![&RESENE[..]],
			Palette::Colorsteel => vec![&COLORSTEEL[..]],
			Palette::RalClassic => vec![&RAL_CLASSIC[..]],
			Palette::RalF9 => vec![&RAL_F9[..]],
			Palette::Munsell => vec![&MUNSELL[..]],
			Palette::Saccardo => vec![&SACCARDO[..]],
		}
		.into_iter()
		.flat_map(|s| s.iter())
		.collect::<HashSet<&&str>>();

		set.into_iter()
			.choose(&mut rand::thread_rng())
			.unwrap()
			.to_string()
	}
}

pub const COMMON: [&str; 16] = [
	"Beige", "Black", "Blue", "Brown", "Cyan", "Gray", "Green", "Magenta", "Orange", "Pink",
	"Purple", "Red", "Teal", "Violet", "White", "Yellow",
];

// From https://en.wikipedia.org/wiki/List_of_colors_(alphabetical)
// excluding crayola colours and colours with non-descriptive names
pub const EXTENDED: [&str; 918] = [
	"Acid green",
	"Aero",
	"African violet",
	"Air superiority blue",
	"Alabaster",
	"Alice blue",
	"Alizarin",
	"Alloy orange",
	"Almond",
	"Amaranth",
	"Amaranth deep purple",
	"Amaranth pink",
	"Amaranth purple",
	"Amazon",
	"Amber",
	"Amethyst",
	"Android green",
	"Antique bronze",
	"Antique fuchsia",
	"Antique ruby",
	"Antique white",
	"Apricot",
	"Aqua",
	"Aquamarine",
	"Arctic lime",
	"Artichoke green",
	"Arylide yellow",
	"Ash gray",
	"Atomic tangerine",
	"Aureolin",
	"Azure",
	"Baby blue",
	"Baby blue eyes",
	"Baby pink",
	"Baby powder",
	"Baker-Miller pink",
	"Barbie pink",
	"Barn red",
	"Battleship grey",
	"Beau blue",
	"Beaver",
	"Beige",
	"B'dazzled blue",
	"Big dip o’ruby",
	"Bisque",
	"Bistre",
	"Bistre brown",
	"Bitter lemon",
	"Bittersweet shimmer",
	"Black",
	"Black bean",
	"Black olive",
	"Blanched almond",
	"Blast-off bronze",
	"Bleu de France",
	"Blood red",
	"Blue",
	"Blue-gray",
	"Blue-green",
	"Blue sapphire",
	"Blue-violet",
	"Blue yonder",
	"Blush",
	"Bole",
	"Bone",
	"Bright green",
	"Bright lilac",
	"Bright navy blue",
	"Bright pink",
	"Bright turquoise",
	"Brink pink",
	"British racing green",
	"Bronze",
	"Brown",
	"Bud green",
	"Buff",
	"Burgundy",
	"Burlywood",
	"Burnt orange",
	"Burnt sienna",
	"Burnt umber",
	"Byzantine",
	"Byzantium",
	"Cadet",
	"Cadet blue",
	"Cadet grey",
	"Cadmium green",
	"Cadmium orange",
	"Cadmium red",
	"Cadmium yellow",
	"Café au lait",
	"Café Noir",
	"Cambridge blue",
	"Camel",
	"Cameo pink",
	"Canary yellow",
	"Candy apple red",
	"Candy pink",
	"Cardinal",
	"Caribbean green",
	"Carmine",
	"Carnation pink",
	"Carolina blue",
	"Carrot orange",
	"Catawba",
	"Celadon",
	"Celeste",
	"Cerise",
	"Cerulean",
	"Cerulean blue",
	"Cerulean frost",
	"Champagne",
	"Champagne pink",
	"Charcoal",
	"Charleston green",
	"Charm pink",
	"Chartreuse",
	"Cherry blossom pink",
	"Chestnut",
	"China pink",
	"Chinese red",
	"Chinese violet",
	"Chocolate",
	"Cinereous",
	"Citrine",
	"Citron",
	"Claret",
	"Cobalt blue",
	"Cocoa brown",
	"Coffee",
	"Columbia Blue",
	"Congo pink",
	"Cool grey",
	"Copper",
	"Copper penny",
	"Copper red",
	"Copper rose",
	"Coquelicot",
	"Coral",
	"Coral pink",
	"Cordovan",
	"Cornflower blue",
	"Cornsilk",
	"Cosmic latte",
	"Coyote brown",
	"Cotton candy",
	"Cream",
	"Crimson",
	"Cyan",
	"Cyber yellow",
	"Cyclamen",
	"Dandelion",
	"Dark blue",
	"Dark blue-gray",
	"Dark brown",
	"Dark byzantium",
	"Dark cyan",
	"Dark electric blue",
	"Dark Fuchsia",
	"Dark goldenrod",
	"Dark gray",
	"Dark green",
	"Dark jungle green",
	"Dark khaki",
	"Dark lava",
	"Dark liver",
	"Dark magenta",
	"Dark moss green",
	"Dark olive green",
	"Dark orange",
	"Dark orchid",
	"Dark pastel green",
	"Dark purple",
	"Dark raspberry",
	"Dark red",
	"Dark salmon",
	"Dark sea green",
	"Dark sienna",
	"Dark sky blue",
	"Dark slate blue",
	"Dark slate gray",
	"Dark spring green",
	"Dark tan",
	"Dark turquoise",
	"Dark vanilla",
	"Dark violet",
	"Dartmouth green",
	"Davy's grey",
	"Deep cerise",
	"Deep champagne",
	"Deep chestnut",
	"Deep fuchsia",
	"Deep jungle green",
	"Deep lemon",
	"Deep mauve",
	"Deep pink",
	"Deep sky blue",
	"Deep Taupe",
	"Desert",
	"Desert sand",
	"Dim gray",
	"Dodger blue",
	"Dogwood rose",
	"Duke blue",
	"Dutch white",
	"Earth yellow",
	"Ebony",
	"Ecru",
	"Eerie black",
	"Eggplant",
	"Eggshell",
	"Egyptian blue",
	"Electric blue",
	"Electric indigo",
	"Electric lime",
	"Electric purple",
	"Electric violet",
	"Emerald",
	"Eminence",
	"English lavender",
	"English red",
	"English violet",
	"Eton blue",
	"Fallow",
	"Falu red",
	"Fandango",
	"Fandango pink",
	"Fashion fuchsia",
	"Fawn",
	"Feldgrau",
	"Fern green",
	"Field drab",
	"Firebrick",
	"Fire engine red",
	"Fire opal",
	"Flame",
	"Flax",
	"Flirt",
	"Floral white",
	"Fluorescent blue",
	"Forest green",
	"French beige",
	"French bistre",
	"French blue",
	"French fuchsia",
	"French lilac",
	"French lime",
	"French mauve",
	"French pink",
	"French raspberry",
	"French rose",
	"French sky blue",
	"French violet",
	"Fuchsia",
	"Fuchsia purple",
	"Fuchsia rose",
	"Fulvous",
	"Gainsboro",
	"Gamboge",
	"Garnet",
	"Generic viridian",
	"Ghost white",
	"Glaucous",
	"GO green",
	"Gold",
	"Golden brown",
	"Golden poppy",
	"Golden yellow",
	"Goldenrod",
	"Gray",
	"Green",
	"Green-blue",
	"Green-cyan",
	"Green-yellow",
	"Grullo",
	"Gunmetal",
	"Han blue",
	"Han purple",
	"Hansa yellow",
	"Harlequin",
	"Harvest gold",
	"Heliotrope",
	"Heliotrope gray",
	"Hollywood cerise",
	"Honeydew",
	"Honolulu blue",
	"Hooker's green",
	"Hot fuchsia",
	"Hot magenta",
	"Hot pink",
	"Hunter green",
	"Iceberg",
	"Icterine",
	"Imperial red",
	"India green",
	"Indian red",
	"Indian yellow",
	"Indigo",
	"Indigo dye",
	"International orange",
	"Iris",
	"Isabelline",
	"Italian sky blue",
	"Ivory",
	"Jade",
	"Japanese carmine",
	"Japanese violet",
	"Jasmine",
	"Jazzberry jam",
	"Jet",
	"Jonquil",
	"June bud",
	"Jungle green",
	"Kelly green",
	"Keppel",
	"Khaki",
	"Kobe",
	"Kobi",
	"Kobicha",
	"Kombu green",
	"KSU Purple",
	"La Salle green",
	"Languid lavender",
	"Lanzones",
	"Lapis lazuli",
	"Laser Lemon",
	"Laurel green",
	"Lava",
	"Lavender",
	"Lavender blue",
	"Lavender gray",
	"Lavender indigo",
	"Lavender magenta",
	"Lavender mist",
	"Lavender purple",
	"Lavender rose",
	"Lemon",
	"Lemon chiffon",
	"Lemon curry",
	"Lemon glacier",
	"Lemon iced tea",
	"Lemon lime",
	"Lemon meringue",
	"Lemon yellow",
	"Licorice",
	"Light brown",
	"Light carmine pink",
	"Light chocolate cosmos",
	"Light cobalt blue",
	"Light cornflower blue",
	"Light crimson",
	"Light cyan",
	"Light French beige",
	"Light fuchsia pink",
	"Light gold",
	"Light grayish magenta",
	"Light medium orchid",
	"Light moss green",
	"Light orchid",
	"Light pastel purple",
	"Light periwinkle",
	"Light red",
	"Light red ochre",
	"Light salmon pink",
	"Light sea green",
	"Light silver",
	"Light Thulian pink",
	"Lilac",
	"Lime",
	"Lime green",
	"Limerick",
	"Lincoln green",
	"Linen",
	"Lion",
	"Liseran purple",
	"Little boy blue",
	"Little girl pink",
	"Liver",
	"Liver chestnut",
	"Livid",
	"Lotion",
	"Lotion blue",
	"Lotion pink",
	"Lust",
	"Maastricht Blue",
	"Magenta",
	"Mahogany",
	"Maize",
	"Majorelle Blue",
	"Malachite",
	"Mango",
	"Mango green",
	"Mantis",
	"Mardi Gras",
	"Marigold",
	"Maroon",
	"Mauve",
	"Mauve taupe",
	"Maximum orange",
	"Maximum pink",
	"Maximum red",
	"Maximum violet",
	"Maximum yellow",
	"May green",
	"Maya blue",
	"Medium aquamarine",
	"Medium blue",
	"Medium candy apple red",
	"Medium carmine",
	"Medium champagne",
	"Medium electric blue",
	"Medium green",
	"Medium jungle green",
	"Medium lavender magenta",
	"Medium orange",
	"Medium orchid",
	"Medium Persian blue",
	"Medium pink",
	"Medium purple",
	"Medium red",
	"Medium red-violet",
	"Medium ruby",
	"Medium sea green",
	"Medium sky blue",
	"Medium slate blue",
	"Medium spring bud",
	"Medium spring green",
	"Medium taupe",
	"Medium turquoise",
	"Medium Tuscan red",
	"Medium vermilion",
	"Medium violet",
	"Medium violet-red",
	"Medium yellow",
	"Mellow apricot",
	"Mellow yellow",
	"Melon",
	"Menthol",
	"Metallic blue",
	"Metallic bronze",
	"Metallic brown",
	"Metallic gold",
	"Metallic green",
	"Metallic orange",
	"Metallic pink",
	"Metallic red",
	"Metallic silver",
	"Metallic violet",
	"Metallic yellow",
	"Mexican pink",
	"Microsoft blue",
	"Microsoft Edge blue",
	"Microsoft green",
	"Microsoft red",
	"Microsoft yellow",
	"Midnight blue",
	"Midnight green",
	"Mikado yellow",
	"Milk",
	"Milk chocolate",
	"Mimi pink",
	"Mindaro",
	"Ming",
	"Minion yellow",
	"Mint",
	"Mint cream",
	"Mint green",
	"Misty rose",
	"Moccasin",
	"Mocha",
	"Mode beige",
	"Moonstone",
	"Moonstone blue",
	"Mordant red 19",
	"Morning blue",
	"Moss green",
	"Mountbatten pink",
	"MSU green",
	"Mud",
	"Mughal green",
	"Mulberry",
	"Mustard",
	"Mustard brown",
	"Mustard green",
	"Mustard yellow",
	"Myrtle green",
	"Mystic red",
	"Nadeshiko pink",
	"Napier green",
	"Naples yellow",
	"Navajo white",
	"Navy blue",
	"Navy purple",
	"Neon blue",
	"Neon brown",
	"Neon cyan",
	"Neon fuchsia",
	"Neon gold",
	"Neon gray",
	"Neon dark green",
	"Neon green",
	"Neon pink",
	"Neon purple",
	"Neon red",
	"Neon scarlet",
	"Neon silver",
	"Neon tangerine",
	"New York pink",
	"Nickel",
	"Nintendo red",
	"Non-photo blue",
	"Nyanza",
	"Ocean boat blue",
	"Ochre",
	"Office green",
	"Old burgundy",
	"Old gold",
	"Old heliotrope",
	"Old lace",
	"Old lavender",
	"Old mauve",
	"Old moss green",
	"Old rose",
	"Old silver",
	"Olive",
	"Olive drab",
	"Olive green",
	"Olivine",
	"Onyx",
	"Opal",
	"Opera mauve",
	"Orange",
	"Orange iced tea",
	"Orange-red",
	"Orange soda",
	"Orange-yellow",
	"Orchid",
	"Orchid pink",
	"Orioles orange",
	"Otter brown",
	"Outer Space",
	"Oxblood",
	"Oxford blue",
	"Oxley",
	"Pakistan green",
	"Palatinate blue",
	"Palatinate purple",
	"Pale aqua",
	"Pale blue",
	"Pale brown",
	"Pale carmine",
	"Pale cerulean",
	"Pale chestnut",
	"Pale copper",
	"Pale cornflower blue",
	"Pale cyan",
	"Pale gold",
	"Pale goldenrod",
	"Pale green",
	"Pale lavender",
	"Pale magenta",
	"Pale pink",
	"Pale plum",
	"Pale robin egg blue",
	"Pale silver",
	"Pale spring bud",
	"Pale taupe",
	"Pale turquoise",
	"Pale violet",
	"Pale violet-red",
	"Pansy purple",
	"Paolo Veronese green",
	"Papaya whip",
	"Paradise pink",
	"Parchment",
	"Paris Green",
	"Pastel blue",
	"Pastel brown",
	"Pastel gray",
	"Pastel green",
	"Pastel magenta",
	"Pastel orange",
	"Pastel pink",
	"Pastel purple",
	"Pastel red",
	"Pastel violet",
	"Pastel yellow",
	"Patriarch",
	"Payne's grey",
	"Peach",
	"Peach puff",
	"Pear",
	"Pearl",
	"Pearl Aqua",
	"Pearly purple",
	"Peridot",
	"Periwinkle",
	"Persian blue",
	"Persian green",
	"Persian indigo",
	"Persian orange",
	"Persian pink",
	"Persian plum",
	"Persian red",
	"Persian rose",
	"Persimmon",
	"Peru",
	"Petal",
	"Philippine blue",
	"Philippine bronze",
	"Philippine brown",
	"Philippine gold",
	"Philippine golden yellow",
	"Philippine gray",
	"Philippine green",
	"Philippine indigo",
	"Philippine orange",
	"Philippine pink",
	"Philippine red",
	"Philippine silver",
	"Philippine sky blue",
	"Philippine violet",
	"Philippine yellow",
	"Phlox",
	"Phthalo blue",
	"Phthalo green",
	"Picton blue",
	"Pictorial carmine",
	"Piggy pink",
	"Pine green",
	"Pine tree",
	"Pineapple",
	"Pink",
	"Pink Diamond",
	"Pink lace",
	"Pink pearl",
	"Pistachio",
	"Platinum",
	"Plum",
	"Poison Purple",
	"Police blue",
	"Pomp and Power",
	"Portland Orange",
	"Powder blue",
	"Princeton orange",
	"Prune",
	"Prussian blue",
	"Psychedelic purple",
	"Puce",
	"Puce red",
	"Pullman Brown",
	"Pumpkin",
	"Purple",
	"Purple Heart",
	"Purple mountain majesty",
	"Purple navy",
	"Purple pizzazz",
	"Purple taupe",
	"Purpureus",
	"Quartz",
	"Queen blue",
	"Queen pink",
	"Quinacridone magenta",
	"Quincy",
	"Rackley",
	"Radical Red",
	"Raisin black",
	"Rajah",
	"Raspberry",
	"Raw umber",
	"Rebecca Purple",
	"Red",
	"Red-brown",
	"Red cola",
	"Red-orange",
	"Red rum",
	"Red strawberry",
	"Red-violet",
	"Redwood",
	"Registration black",
	"Resolution blue",
	"Rhythm",
	"Rich brilliant lavender",
	"Rich carmine",
	"Rich electric blue",
	"Rich lavender",
	"Rich lilac",
	"Rich maroon",
	"Rifle green",
	"Ripe mango",
	"Roast coffee",
	"Robin egg blue",
	"Rocket metallic",
	"Roman silver",
	"Root beer",
	"Rose",
	"Royal azure",
	"Royal blue",
	"Royal brown",
	"Royal fuchsia",
	"Royal green",
	"Royal orange",
	"Royal pink",
	"Royal red",
	"Royal purple",
	"Royal yellow",
	"Ruby",
	"Rufous",
	"Rum",
	"Russet",
	"Russian green",
	"Russian violet",
	"Rust",
	"Rusty red",
	"Sacramento State green",
	"Saddle brown",
	"Safety orange",
	"Safety yellow",
	"Saffron",
	"Sage",
	"St. Patrick's blue",
	"Salem",
	"Salmon",
	"Salmon Rose",
	"Salmon pink",
	"Samsung blue",
	"Sand",
	"Sand dune",
	"Sandy brown",
	"Sandy taupe",
	"Sap green",
	"Sapphire",
	"Sapphire blue",
	"Satin sheen gold",
	"Scarlet",
	"Schauss pink",
	"School bus yellow",
	"Sea blue",
	"Sea green",
	"Seal brown",
	"Seashell",
	"Selective yellow",
	"Sepia",
	"Shadow blue",
	"Shamrock green",
	"Shandy",
	"Shocking pink",
	"Sienna",
	"Silver",
	"Silver chalice",
	"Silver foil",
	"Silver Lake blue",
	"Silver pink",
	"Silver sand",
	"Sinopia",
	"Skobeloff",
	"Sky blue",
	"Sky magenta",
	"Slate blue",
	"Slate gray",
	"Smalt",
	"Smokey Topaz",
	"Smoky black",
	"Soap",
	"Solid pink",
	"Sonic silver",
	"Spartan Crimson",
	"Space cadet",
	"Spanish bistre",
	"Spanish blue",
	"Spanish carmine",
	"Spanish crimson",
	"Spanish gray",
	"Spanish green",
	"Spanish orange",
	"Spanish pink",
	"Spanish purple",
	"Spanish red",
	"Spanish sky blue",
	"Spanish violet",
	"Spanish viridian",
	"Spanish yellow",
	"Spicy mix",
	"Spring bud",
	"Spring green",
	"Star command blue",
	"Steel blue",
	"Steel pink",
	"Stil de grain yellow",
	"Straw",
	"Stop red",
	"Strawberry iced tea",
	"Strawberry red",
	"Sunglow",
	"Sunray",
	"Sunset",
	"Sunset orange",
	"Super pink",
	"Tan",
	"Tangelo",
	"Tangerine",
	"Tangerine yellow",
	"Tango pink",
	"Taupe",
	"Taupe gray",
	"Tea green",
	"Tea rose",
	"Teal",
	"Teal blue",
	"Teal deer",
	"Teal green",
	"Telemagenta",
	"Temptress",
	"Tenné",
	"Terra cotta",
	"Thistle",
	"Thulian pink",
	"Tickle Me Pink",
	"Tiffany Blue",
	"Tiger's eye",
	"Titanium",
	"Titanium yellow",
	"Tomato",
	"Tomato sauce",
	"Tooth",
	"Topaz",
	"Tractor red",
	"Trolley grey",
	"Tropical rain forest",
	"True blue",
	"Tufts blue",
	"Turkish rose",
	"Turquoise",
	"Turquoise green",
	"Tuscan brown",
	"Tuscan red",
	"Tuscan tan",
	"Tuscany",
	"Twitter blue",
	"Tyrian purple",
	"Ultramarine",
	"Ultramarine blue",
	"Ultra red",
	"Umber",
	"Unbleached silk",
	"United Nations blue",
	"Unmellow yellow",
	"UP maroon",
	"Upsdell red",
	"Urobilin",
	"Vampire black",
	"Van Dyke brown",
	"Vanilla",
	"Vanilla ice",
	"Vegas gold",
	"Venetian red",
	"Verdigris",
	"Vermilion",
	"Veronica",
	"Very light azure",
	"Very light blue",
	"Very light malachite green",
	"Very light tangelo",
	"Very pale orange",
	"Very pale yellow",
	"Vine Green",
	"Violet",
	"Violet-blue",
	"Violin Brown",
	"Viridian",
	"Viridian green",
	"Vista blue",
	"Vivid amber",
	"Vivid auburn",
	"Vivid burgundy",
	"Vivid cerise",
	"Vivid cerulean",
	"Vivid crimson",
	"Vivid gamboge",
	"Vivid lime green",
	"Vivid mulberry",
	"Vivid orange",
	"Vivid orange peel",
	"Vivid orchid",
	"Vivid raspberry",
	"Vivid red",
	"Vivid red-tangelo",
	"Vivid tangelo",
	"Vivid vermilion",
	"Vivid violet",
	"Vivid yellow",
	"Water",
	"Watermelon",
	"Watermelon red",
	"Watermelon Yellow",
	"Waterspout",
	"Wenge",
	"Wheat",
	"White",
	"White chocolate",
	"White coffee",
	"White smoke",
	"Wild orchid",
	"Wild watermelon",
	"Willpower orange",
	"Windsor tan",
	"Wine",
	"Wine red",
	"Wisteria",
	"Wood brown",
	"Xanadu",
	"Yellow",
	"Yellow-green",
	"Yellow rose",
	"YInMn Blue",
	"Zaffre",
	"Zebra White",
	"Zinnwaldite",
];

pub const HTML: [&str; 148] = [
	"AliceBlue",
	"AntiqueWhite",
	"Aqua",
	"Aquamarine",
	"Azure",
	"Beige",
	"Bisque",
	"Black",
	"BlanchedAlmond",
	"Blue",
	"BlueViolet",
	"Brown",
	"BurlyWood",
	"CadetBlue",
	"Chartreuse",
	"Chocolate",
	"Coral",
	"CornflowerBlue",
	"Cornsilk",
	"Crimson",
	"Cyan",
	"DarkBlue",
	"DarkCyan",
	"DarkGoldenRod",
	"DarkGray",
	"DarkGrey",
	"DarkGreen",
	"DarkKhaki",
	"DarkMagenta",
	"DarkOliveGreen",
	"DarkOrange",
	"DarkOrchid",
	"DarkRed",
	"DarkSalmon",
	"DarkSeaGreen",
	"DarkSlateBlue",
	"DarkSlateGray",
	"DarkSlateGrey",
	"DarkTurquoise",
	"DarkViolet",
	"DeepPink",
	"DeepSkyBlue",
	"DimGray",
	"DimGrey",
	"DodgerBlue",
	"FireBrick",
	"FloralWhite",
	"ForestGreen",
	"Fuchsia",
	"Gainsboro",
	"GhostWhite",
	"Gold",
	"GoldenRod",
	"Gray",
	"Grey",
	"Green",
	"GreenYellow",
	"HoneyDew",
	"HotPink",
	"IndianRed",
	"Indigo",
	"Ivory",
	"Khaki",
	"Lavender",
	"LavenderBlush",
	"LawnGreen",
	"LemonChiffon",
	"LightBlue",
	"LightCoral",
	"LightCyan",
	"LightGoldenRodYellow",
	"LightGray",
	"LightGrey",
	"LightGreen",
	"LightPink",
	"LightSalmon",
	"LightSeaGreen",
	"LightSkyBlue",
	"LightSlateGray",
	"LightSlateGrey",
	"LightSteelBlue",
	"LightYellow",
	"Lime",
	"LimeGreen",
	"Linen",
	"Magenta",
	"Maroon",
	"MediumAquaMarine",
	"MediumBlue",
	"MediumOrchid",
	"MediumPurple",
	"MediumSeaGreen",
	"MediumSlateBlue",
	"MediumSpringGreen",
	"MediumTurquoise",
	"MediumVioletRed",
	"MidnightBlue",
	"MintCream",
	"MistyRose",
	"Moccasin",
	"NavajoWhite",
	"Navy",
	"OldLace",
	"Olive",
	"OliveDrab",
	"Orange",
	"OrangeRed",
	"Orchid",
	"PaleGoldenRod",
	"PaleGreen",
	"PaleTurquoise",
	"PaleVioletRed",
	"PapayaWhip",
	"PeachPuff",
	"Peru",
	"Pink",
	"Plum",
	"PowderBlue",
	"Purple",
	"RebeccaPurple",
	"Red",
	"RosyBrown",
	"RoyalBlue",
	"SaddleBrown",
	"Salmon",
	"SandyBrown",
	"SeaGreen",
	"SeaShell",
	"Sienna",
	"Silver",
	"SkyBlue",
	"SlateBlue",
	"SlateGray",
	"SlateGrey",
	"Snow",
	"SpringGreen",
	"SteelBlue",
	"Tan",
	"Teal",
	"Thistle",
	"Tomato",
	"Turquoise",
	"Violet",
	"Wheat",
	"White",
	"WhiteSmoke",
	"Yellow",
	"YellowGreen",
];

pub const BEER: [&str; 29] = [
	"Pale lager",
	"Witbier",
	"Pilsener",
	"Berliner Weisse",
	"Maibock",
	"Blonde Ale",
	"Weissbier",
	"American Pale Ale",
	"India Pale Ale",
	"Weissbier",
	"Saison",
	"English Bitter",
	"Bière de Garde",
	"Double IPA",
	"Dark lager",
	"Vienna lager",
	"Märzen",
	"Amber Ale",
	"Brown Ale",
	"Bock",
	"Dunkel",
	"Dunkelweizen",
	"Irish Dry Stout",
	"Doppelbock",
	"Porter",
	"Stout",
	"Foreign Stout",
	"Baltic Porter",
	"Imperial Stout",
];

// From https://web.archive.org/web/20121021004703/http://tx4.us/nbs/nbsstamp.htm
pub const POSTAGE_STAMP: [&str; 178] = [
	"apple green",
	"bistre",
	"",
	"bistre brown",
	"black",
	"black brown",
	"black violet",
	"blue",
	"blue black",
	"blue gray",
	"blue green",
	"blue violet",
	"brick red",
	"bright blue",
	"bright blue green",
	"bright green",
	"bright red violet",
	"bright rose",
	"bright rose violet",
	"bright ultramarine",
	"bright violet",
	"bright yellow",
	"brown",
	"brown bistre",
	"brown-black",
	"brown carmine",
	"brown lake",
	"brown olive",
	"brown orange",
	"brown purple",
	"brown red",
	"brown violet",
	"buff",
	"carmine",
	"carmine lake",
	"carmine rose",
	"cerise",
	"chalky blue",
	"chestnut brown",
	"chocolate",
	"claret",
	"claret brown",
	"crimson",
	"dark blue",
	"dark blue green",
	"dark brown",
	"dark carmine",
	"dark gray",
	"dark green",
	"dark ochre",
	"dark olive",
	"dark olive green",
	"dark red brown",
	"dark rose",
	"dark slate green",
	"dark violet",
	"dark violet brown",
	"deep bistre",
	"deep blue",
	"deep brown",
	"deep claret",
	"deep green",
	"deep lake",
	"deep magenta",
	"deep olive green",
	"deep orange",
	"deep plum",
	"deep ultramarine",
	"deep violet",
	"dull blue",
	"dull buff",
	"dull green",
	"dull lilac",
	"dull orange",
	"dull red",
	"dull rose",
	"dull vermilion",
	"dull violet",
	"dull yellow",
	"emerald",
	"fawn",
	"gray",
	"gray bistre",
	"gray black",
	"gray blue",
	"gray brown",
	"gray green",
	"gray lilac",
	"gray violet",
	"green",
	"greenish black",
	"greenish blue",
	"henna brown",
	"indigo",
	"lake",
	"lemon",
	"lemon yellow",
	"light blue",
	"light brown",
	"light green",
	"light olive green",
	"light red brown",
	"lilac",
	"lilac brown",
	"lilac gray",
	"lilac rose",
	"magenta",
	"maroon",
	"mauve",
	"milky blue",
	"myrtle green",
	"ochre",
	"olive",
	"olive bistre",
	"olive black",
	"olive brown",
	"olive gray",
	"olive green",
	"olive yellow",
	"orange",
	"orange brown",
	"orange buff",
	"orange red",
	"orange vermilion",
	"orange yellow",
	"pale blue",
	"pale brown",
	"pale gray green",
	"pale green",
	"pale lilac",
	"pale olive green",
	"pale yellow-green",
	"peacock blue",
	"pink",
	"plum",
	"prussian blue",
	"prussian green",
	"purple",
	"purple brown",
	"purplish bistre",
	"red",
	"red brown",
	"reddish brown",
	"red lilac",
	"red orange",
	"red purple",
	"red violet",
	"rose",
	"rose brown",
	"rose carmine",
	"rose lake",
	"rose lilac",
	"rose pink",
	"rose red",
	"rose violet",
	"royal blue",
	"salmon",
	"salmon rose",
	"scarlet",
	"sepia",
	"slate",
	"slate blue",
	"slate green",
	"straw",
	"turquoise blue",
	"turquoise green",
	"ultramarine",
	"umber brown",
	"vermilion",
	"violet",
	"violet black",
	"violet blue",
	"violet brown",
	"yellow",
	"yellow brown",
	"yellow buff",
	"yellow green",
	"yellow orange",
];

pub const CRAYOLA_STANDARD: [&str; 162] = [
	"Red",
	"Maroon",
	"Scarlet",
	"Brick Red",
	"English Vermilion",
	"Madder Lake",
	"Permanent Geranium Lake",
	"Maximum Red",
	"Chestnut",
	"Orange-Red",
	"Sunset Orange",
	"Bittersweet",
	"Dark Venetian Red",
	"Venetian Red",
	"Light Venetian Red",
	"Vivid Tangerine",
	"Middle Red",
	"Burnt Orange",
	"Red-Orange",
	"Orange",
	"Macaroni and Cheese",
	"Middle Yellow Red",
	"Mango Tango",
	"Yellow-Orange",
	"Maximum Yellow Red",
	"Banana Mania",
	"Maize",
	"Orange-Yellow",
	"Goldenrod",
	"Dandelion",
	"Yellow",
	"Green-Yellow",
	"Middle Yellow",
	"Olive Green",
	"Spring Green",
	"Maximum Yellow",
	"Canary",
	"Lemon Yellow",
	"Maximum Green Yellow",
	"Middle Green Yellow",
	"Inchworm",
	"Light Chrome Green",
	"Yellow-Green",
	"Maximum Green",
	"Asparagus",
	"Granny Smith Apple",
	"Fern",
	"Middle Green",
	"Green",
	"Medium Chrome Green",
	"Forest Green",
	"Sea Green",
	"Shamrock",
	"Mountain Meadow",
	"Jungle Green",
	"Caribbean Green",
	"Tropical Rain Forest",
	"Middle Blue Green",
	"Pine Green",
	"Maximum Blue Green",
	"Robin's Egg Blue",
	"Teal Blue",
	"Light Blue",
	"Aquamarine",
	"Turquoise Blue",
	"Outer Space",
	"Sky Blue",
	"Middle Blue",
	"Blue-Green",
	"Pacific Blue",
	"Cerulean",
	"Maximum Blue",
	"Blue",
	"Cerulean Blue",
	"Cornflower",
	"Green-Blue",
	"Midnight Blue",
	"Navy Blue",
	"Denim",
	"Cadet Blue",
	"Periwinkle",
	"Bluetiful",
	"Wild Blue Yonder",
	"Indigo",
	"Manatee",
	"Cobalt Blue",
	"Celestial Blue",
	"Blue Bell",
	"Maximum Blue Purple",
	"Violet-Blue",
	"Blue-Violet",
	"Ultramarine Blue",
	"Middle Blue Purple",
	"Purple Heart",
	"Royal Purple",
	"Violet",
	"Medium Violet",
	"Wisteria",
	"Lavender",
	"Vivid Violet",
	"Maximum Purple",
	"Purple Mountains' Majesty",
	"Fuchsia",
	"Pink Flamingo",
	"Brilliant Rose",
	"Orchid",
	"Plum",
	"Medium Rose",
	"Thistle",
	"Mulberry",
	"Red-Violet",
	"Middle Purple",
	"Maximum Red Purple",
	"Jazzberry Jam",
	"Eggplant",
	"Magenta",
	"Cerise",
	"Wild Strawberry",
	"Cotton Candy",
	"Carnation Pink",
	"Violet-Red",
	"Razzmatazz",
	"Piggy Pink",
	"Carmine",
	"Blush",
	"Tickle Me Pink",
	"Mauvelous",
	"Salmon",
	"Middle Red Purple",
	"Mahogany",
	"Melon",
	"Pink Sherbert",
	"Burnt Sienna",
	"Brown",
	"Sepia",
	"Fuzzy Wuzzy",
	"Beaver",
	"Tumbleweed",
	"Raw Sienna",
	"Van Dyke Brown",
	"Tan",
	"Desert Sand",
	"Peach",
	"Burnt Umber",
	"Apricot",
	"Almond",
	"Raw Umber",
	"Shadow",
	"Gold",
	"Silver",
	"Copper",
	"Antique Brass",
	"Black",
	"Charcoal Gray",
	"Gray",
	"Blue-Gray",
	"Timberwolf",
	"White",
	"Crayellow",
	"Cool Mint",
	"Oatmeal",
	"Powder Blue",
];

pub const CRAYOLA_FLUORESCENT: [&str; 16] = [
	"Radical Red",
	"Wild Watermelon",
	"Outrageous Orange",
	"Atomic Tangerine",
	"Neon Carrot",
	"Sunglow",
	"Laser Lemon",
	"Unmellow Yellow",
	"Electric Lime",
	"Screamin' Green",
	"Magic Mint",
	"Blizzard Blue",
	"Shocking Pink",
	"Razzle Dazzle Rose",
	"Hot Magenta",
	"Purple Pizzazz",
];

pub const CRAYOLA_METALLIC: [&str; 16] = [
	"Aged Copper",
	"Aztec Gold",
	"Bluetonium",
	"Brass",
	"Bronze",
	"Cadmium Red",
	"Cast Iron",
	"Cobalt Blue",
	"Copper",
	"Gold",
	"Kryptonite",
	"Rust",
	"Silver",
	"Steel Blue",
	"Tarnished Gold",
	"Titanium",
];

pub const CRAYOLA_SWIRL: [&str; 24] = [
	"Aztec Gold",
	"Burnished Brown",
	"Cerulean Frost",
	"Cinnamon Satin",
	"Copper Penny",
	"Cosmic Cobalt",
	"Glossy Grape",
	"Granite Gray",
	"Green Sheen",
	"Lilac Luster",
	"Misty Moss",
	"Mystic Maroon",
	"Pearly Purple",
	"Pewter Blue",
	"Polished Pine",
	"Quick Silver",
	"Rose Dust",
	"Rusty Red",
	"Shadow Blue",
	"Shiny Shamrock",
	"Steel Teal",
	"Sugar Plum",
	"Twilight Lavender",
	"Wintergreen Dream",
];

pub const CRAYOLA_GEMS: [&str; 16] = [
	"Amethyst",
	"Citrine",
	"Emerald",
	"Jade",
	"Jasper",
	"Lapis Lazuli",
	"Malachite",
	"Moonstone",
	"Onyx",
	"Peridot",
	"Pink Pearl",
	"Rose Quartz",
	"Ruby",
	"Sapphire",
	"Smokey Topaz",
	"Tiger's Eye",
];

pub const RESENE: [&str; 266] = [
	"Ash grey",
	"Oyster grey",
	"Portland",
	"Grey",
	"Goose grey",
	"Sea mist",
	"Goosewing",
	"Flint grey",
	"Flint",
	"Storm grey",
	"Greyfriar",
	"Black",
	"White",
	"Lupin pink",
	"Candy floss",
	"Pink wafer",
	"Pink",
	"Clover pink",
	"Corinth",
	"Fontana",
	"Victoria plum",
	"Aubergine",
	"Plum",
	"Deep plum",
	"Loganberry",
	"Violet",
	"Purple",
	"Deep pink",
	"Bordeaux",
	"Rosepetal",
	"Pastel pink",
	"Dawn pink",
	"Dusty pink",
	"Tea rose",
	"Tearose",
	"Beige",
	"Sable",
	"Sierra",
	"Brown",
	"Saracen",
	"Orchid pink",
	"Parisian pink",
	"Shell",
	"Soft red",
	"Autumn brown",
	"Rosevale",
	"Brick red",
	"Copperbeech",
	"Maroon",
	"Robin",
	"Misty red",
	"Tawny",
	"Dark cherry",
	"Russet",
	"Monarch",
	"Rose pink",
	"Petal",
	"Salmon red",
	"Lobster",
	"Azalea",
	"Poppy",
	"Carnival red",
	"Red",
	"Peach",
	"Cameo",
	"Light orange",
	"Leather brown",
	"Brownstone",
	"Saddle brown",
	"Saddle",
	"Orange",
	"Mid tan",
	"Kalahari",
	"Cinnamon",
	"Teak",
	"Mace",
	"Mellow apricot",
	"Apricot",
	"Mandarin orange",
	"Clementine",
	"Calendula",
	"Maori brown",
	"Nectarine",
	"Magnolia",
	"Honey beige",
	"Fawn",
	"Sandstone",
	"Antelope",
	"Beaver brown",
	"Beaver",
	"Bitter chocolate",
	"Vandyke",
	"Honeysuckle cream",
	"Blush stone",
	"Fudge",
	"Butterscotch",
	"Bamboo",
	"Caramel",
	"Bracken",
	"Coffee",
	"Bison",
	"Yellow",
	"Golden yellow",
	"Amber",
	"Goldcup",
	"Dawn grey",
	"Sink grey",
	"Flake grey",
	"Nimbus grey",
	"Wood ash",
	"Woodash",
	"Charcoal grey",
	"Storm",
	"Rhino",
	"Creamy white",
	"Ivory",
	"Gardenia",
	"Oatmeal",
	"Greystone",
	"Hopsack",
	"Lizard grey",
	"Turtle green",
	"Turtle",
	"Vandyke brown",
	"Ironstone",
	"Champagne",
	"Buttermilk",
	"Vanilla",
	"Pollen",
	"Wheat",
	"Golden bronze",
	"Savannah",
	"Yellow brown",
	"Dark olive",
	"Saluki",
	"Seaweed",
	"Riverbed",
	"Golden maize",
	"Banana",
	"Capricorn",
	"Light olive",
	"French mustard",
	"Florida",
	"Pale primrose",
	"Pale lemon",
	"Jonquil",
	"Light grapefruit",
	"Forsythia",
	"Sunflower yellow",
	"Canary",
	"Aztec",
	"Canary Yellow",
	"Sea foam",
	"Seafoam",
	"Green Mist",
	"Willow",
	"Mineral green",
	"Opaline",
	"Moorland",
	"Green",
	"Spruce green",
	"Thyme",
	"Chive",
	"Midnight green",
	"Juniper",
	"Light yellow",
	"Green haze",
	"Catkin",
	"Ivy green",
	"Orchard",
	"Greengage",
	"Sapling",
	"Springleaf",
	"Dark laurel",
	"Tundra",
	"Sherwood",
	"Pale lime",
	"Citrine",
	"Linden green",
	"Linden",
	"Glacial green",
	"Alpine",
	"Iceplant green",
	"Braemar",
	"Holly green",
	"Hollybush",
	"Moss green",
	"Conifer",
	"Light green",
	"Bright green",
	"Goblin",
	"Garland",
	"Irish green",
	"Avarice",
	"Verona",
	"Mid grey",
	"Duckegg",
	"Duck egg blue",
	"Reef green",
	"Orion",
	"Deep green",
	"Dark jade",
	"Scarab",
	"Turquoise",
	"Aquamarine",
	"Seafarer",
	"Lido",
	"Blue mink",
	"Silver haze",
	"Heron",
	"Squirrel grey",
	"Tideway",
	"Dark admiralty grey",
	"Merlin",
	"Raven",
	"Ice blue",
	"Spindrift",
	"Blue",
	"Corvette blue",
	"Pigeon",
	"Fathom blue",
	"Deep river",
	"Dolphin",
	"Dresden blue",
	"Crystal blue",
	"Astral blue",
	"Pinefrost",
	"Ribbon blue",
	"Cirrus",
	"Delphinium Blue",
	"Mermaid",
	"Larkspur",
	"Tartan blue",
	"Cobalt blue",
	"Regatta",
	"Porcelain blue",
	"Pompadour",
	"Larkspur blue",
	"Viking",
	"Duchess blue",
	"Midnight",
	"Powder blue",
	"Sapphire blue",
	"Maritime",
	"Trafalgar",
	"Cornflower blue",
	"Corfu",
	"Cornflower",
	"Pearl grey",
	"Swansdown",
	"Pale lavender",
	"Haze",
	"Dove",
	"Soft blue",
	"Kashmir",
	"Nightshade",
	"Deep purple",
	"Soft purple",
	"Purple heather",
	"Heather",
	"Pageant",
	"Pale lilac",
	"Mallow",
	"Amethyst",
	"Regal violet",
	"Regalia",
];

// https://www.colorsteel.co.nz/products/colours (retrieved 2023-11-05)
pub const COLORSTEEL: [&str; 22] = [
	"Snow Stone",
	"Tidal Drift",
	"Flax Pod",
	"Cloud",
	"Titania",
	"Gull Grey",
	"Sandstone Grey",
	"New Denim Blue",
	"Grey Friars",
	"Windsor Grey",
	"Thunder Grey",
	"Slate",
	"Ironsand",
	"Ebony",
	"Lichen",
	"Mist Green",
	"Permanent Green",
	"Karaka",
	"Desert Sand",
	"Scoria",
	"Pioneer Red",
	"Lignite",
];

// From https://en.wikipedia.org/wiki/List_of_RAL_colours#Overview
pub const RAL_CLASSIC: [&str; 211] = [
	"Green beige",
	"Beige",
	"Sand yellow",
	"Signal yellow",
	"Golden yellow",
	"Honey yellow",
	"Maize yellow",
	"Daffodil yellow",
	"Brown beige",
	"Lemon yellow",
	"Oyster white",
	"Ivory",
	"Light ivory",
	"Sulfur yellow",
	"Saffron yellow",
	"Zinc yellow",
	"Grey beige",
	"Olive yellow",
	"Colza yellow",
	"Traffic yellow",
	"Ochre yellow",
	"Luminous yellow",
	"Curry",
	"Melon yellow",
	"Broom yellow",
	"Dahlia yellow",
	"Pastel yellow",
	"Pearl beige",
	"Pearl gold",
	"Sun yellow",
	"Yellow orange",
	"Red orange",
	"Vermilion",
	"Pastel orange",
	"Pure orange",
	"Luminous orange",
	"Luminous bright orange",
	"Bright red orange",
	"Traffic orange",
	"Signal orange",
	"Deep orange",
	"Salmon orange",
	"Pearl orange",
	"RAL orange",
	"Flame red",
	"Signal red",
	"Carmine red",
	"Ruby red",
	"Purple red",
	"Wine red",
	"Black red",
	"Oxide red",
	"Brown red",
	"Beige red",
	"Tomato red",
	"Antique pink",
	"Light pink",
	"Coral red",
	"Rose",
	"Strawberry red",
	"Traffic red",
	"Salmon pink",
	"Luminous red",
	"Luminous bright red",
	"Raspberry red",
	"Pure red",
	"Orient red",
	"Pearl ruby red",
	"Pearl pink",
	"Red lilac",
	"Red violet",
	"Heather violet",
	"Claret violet",
	"Blue lilac",
	"Traffic purple",
	"Purple violet",
	"Signal violet",
	"Pastel violet",
	"Telemagenta",
	"Pearl violet",
	"Pearl blackberry",
	"Violet blue",
	"Green blue",
	"Ultramarine blue",
	"Sapphire blue",
	"Black blue",
	"Signal blue",
	"Brilliant blue",
	"Grey blue",
	"Azure blue",
	"Gentian blue",
	"Steel blue",
	"Light blue",
	"Cobalt blue",
	"Pigeon blue",
	"Sky blue",
	"Traffic blue",
	"Turquoise blue",
	"Capri blue",
	"Ocean blue",
	"Water blue",
	"Night blue",
	"Distant blue",
	"Pastel blue",
	"Pearl Gentian blue",
	"Pearl night blue",
	"Patina green",
	"Emerald green",
	"Leaf green",
	"Olive green",
	"Blue green",
	"Moss green",
	"Grey olive",
	"Bottle green",
	"Brown green",
	"Fir green",
	"Grass green",
	"Reseda green",
	"Black green",
	"Reed green",
	"Yellow olive",
	"Black olive",
	"Turquoise green",
	"May green",
	"Yellow green",
	"Pastel green",
	"Chrome green",
	"Pale green",
	"Olive-drab/brown olive",
	"Traffic green",
	"Fern green",
	"Opal green",
	"Light green",
	"Pine green",
	"Mint green",
	"Signal green",
	"Mint turquoise",
	"Pastel turquoise",
	"Pearl green",
	"Pearl opal green",
	"Pure green",
	"Luminous green",
	"Squirrel grey",
	"Silver grey",
	"Olive grey",
	"Moss grey",
	"Signal grey",
	"Mouse grey",
	"Beige grey",
	"Khaki grey",
	"Green grey",
	"Tarpaulin grey",
	"Iron grey",
	"Basalt grey",
	"Brown grey",
	"Slate grey",
	"Anthracite grey",
	"Black grey",
	"Umbra grey",
	"Concrete grey",
	"Graphite grey",
	"Granite grey",
	"Stone grey",
	"Blue grey",
	"Pebble grey",
	"Cement grey",
	"Yellow grey",
	"Light grey",
	"Platinum grey",
	"Dusty grey",
	"Agate grey",
	"Quartz grey",
	"Window grey",
	"Traffic grey",
	"Silk grey",
	"Pearl mouse grey",
	"Green brown",
	"Ochre brown",
	"Signal brown",
	"Clay brown",
	"Copper brown",
	"Fawn brown",
	"Olive brown",
	"Nut brown",
	"Red brown",
	"Sepia brown",
	"Chestnut brown",
	"Mahogany brown",
	"Chocolate brown",
	"Grey brown",
	"Black brown",
	"Orange brown",
	"Beige brown",
	"Pale brown",
	"Terra brown",
	"Pearl copper",
	"Cream",
	"Grey white",
	"Signal white",
	"Signal black",
	"Jet black",
	"White aluminium",
	"Grey aluminium",
	"Pure white",
	"Graphite black",
	"Clean room white",
	"Traffic white",
	"Traffic black",
	"Papyrus white",
	"Pearl light grey",
	"Pearl dark grey",
];

pub const RAL_F9: [&str; 8] = [
	"Sand beige",
	"Clay beige",
	"Bronze green",
	"Light olive",
	"Camouflage grey",
	"Leather brown",
	"Sand brown",
	"Tar black",
];

// From https://web.archive.org/web/20121103030619/http://tx4.us/nbs-iscc.htm
pub const MUNSELL: [&str; 278] = [
	"Vivid Pink",
	"Strong Pink",
	"Deep Pink",
	"Light Pink",
	"Moderate Pink",
	"Dark Pink",
	"Pale Pink",
	"Grayish Pink",
	"Pinkish White",
	"Pinkish Gray",
	"Vivid Red",
	"Strong Red",
	"Deep Red",
	"Very Deep Red",
	"Moderate Red",
	"Dark Red",
	"Very Dark Red",
	"Light Grayish Red",
	"Grayish Red",
	"Dark Grayish Red",
	"Blackish Red",
	"Reddish Gray",
	"Dark Reddish Gray",
	"Reddish Black",
	"Vivid Yellowish Pink",
	"Strong Yellowish Pink",
	"Deep Yellowish Pink",
	"Light Yellowish Pink",
	"Moderate Yellowish Pink",
	"Dark Yellowish Pink",
	"Pale Yellowish Pink",
	"Grayish Yellowish Pink",
	"Brownish Pink",
	"Vivid Reddish Orange",
	"Strong Reddish Orange",
	"Deep Reddish Orange",
	"Moderate Reddish Orange",
	"Dark Reddish Orange",
	"Grayish Reddish Orange",
	"Strong Reddish Brown",
	"Deep Reddish Brown",
	"Light Reddish Brown",
	"Moderate Reddish Brown",
	"Dark Reddish Brown",
	"Light Grayish Reddish Brown",
	"Grayish Reddish Brown",
	"Dark Grayish Reddish Brown",
	"Vivid Orange",
	"Brilliant Orange",
	"Strong Orange",
	"Deep Orange",
	"Light Orange",
	"Moderate Orange",
	"Brownish Orange",
	"Strong Brown",
	"Deep Brown",
	"Light Brown",
	"Moderate Brown",
	"Dark Brown",
	"Light Grayish Brown",
	"Grayish Brown",
	"Dark Grayish Brown",
	"Light Brownish Gray",
	"Brownish Gray",
	"Brownish Black",
	"Vivid Orange Yellow",
	"Brilliant Orange Yellow",
	"Strong Orange Yellow",
	"Deep Orange Yellow",
	"Light Orange Yellow",
	"Moderate Orange Yellow",
	"Dark Orange Yellow",
	"Pale Orange Yellow",
	"Strong Yellowish Brown",
	"Deep Yellowish Brown",
	"Light Yellowish Brown",
	"Moderate Yellowish Brown",
	"Dark Yellowish Brown",
	"Light Grayish Yellowish Brown",
	"Grayish Yellowish Brown",
	"Dark Grayish Yellowish Brown",
	"Vivid Yellow",
	"Brilliant Yellow",
	"Strong Yellow",
	"Deep Yellow",
	"Light Yellow",
	"Moderate Yellow",
	"Dark Yellow",
	"Pale Yellow",
	"Grayish Yellow",
	"Dark Grayish Yellow",
	"Yellowish White",
	"Yellowish Gray",
	"Light Olive Brown",
	"Moderate Olive Brown",
	"Dark Olive Brown",
	"Vivid Greenish Yellow",
	"Brilliant Greenish Yellow",
	"Strong Greenish Yellow",
	"Deep Greenish Yellow",
	"Light Greenish Yellow",
	"Moderate Greenish Yellow",
	"Dark Greenish Yellow",
	"Pale Greenish Yellow",
	"Grayish Greenish Yellow",
	"Light Olive",
	"Moderate Olive",
	"Dark Olive",
	"Light Grayish Olive",
	"Grayish Olive",
	"Dark Grayish Olive",
	"Light Olive Gray",
	"Olive Gray",
	"Olive Black",
	"Vivid Yellow Green",
	"Brilliant Yellow Green",
	"Strong Yellow Green",
	"Deep Yellow Green",
	"Light Yellow Green",
	"Moderate Yellow Green",
	"Pale Yellow Green",
	"Grayish Yellow Green",
	"Strong Olive Green",
	"Deep Olive Green",
	"Moderate Olive Green",
	"Dark Olive Green",
	"Grayish Olive Green",
	"Dark Grayish Olive Green",
	"Vivid Yellowish Green",
	"Brilliant Yellowish Green",
	"Strong Yellowish Green",
	"Deep Yellowish Green",
	"Very Deep Yellowish Green",
	"Very Light Yellowish Green",
	"Light Yellowish Green",
	"Moderate Yellowish Green",
	"Dark Yellowish Green",
	"Very Dark Yellowish Green",
	"Vivid Green",
	"Brilliant Green",
	"Strong Green",
	"Deep Green",
	"Very Light Green",
	"Light Green",
	"Moderate Green",
	"Dark Green",
	"Very Dark Green",
	"Very Pale Green",
	"Pale Green",
	"Grayish Green",
	"Dark Grayish Green",
	"Blackish Green",
	"Greenish White",
	"Light Greenish Gray",
	"Greenish Gray",
	"Dark Greenish Gray",
	"Greenish Black",
	"Vivid Bluish Green",
	"Brilliant Bluish Green",
	"Strong Bluish Green",
	"Deep Bluish Green",
	"Very Light Bluish Green",
	"Light Bluish Green",
	"Moderate Bluish Green",
	"Dark Bluish Green",
	"Very Dark Bluish Green",
	"Vivid Greenish Blue",
	"Brilliant Greenish Blue",
	"Strong Greenish Blue",
	"Deep Greenish Blue",
	"Very Light Greenish Blue",
	"Light Greenish Blue",
	"Moderate Greenish Blue",
	"Dark Greenish Blue",
	"Very Dark Greenish Blue",
	"Vivid Blue",
	"Ultramarine",
	"Brilliant Blue",
	"Celestial Blue",
	"Strong Blue",
	"Bright Blue",
	"Deep Blue",
	"Royal Blue",
	"Very Light Blue",
	"Baby Blue",
	"Light Blue",
	"Sky Blue",
	"Moderate Blue",
	"Cerulean Blue",
	"Dark Blue",
	"Navy Blue",
	"Very Pale Blue",
	"Cloud Blue",
	"Pale Blue",
	"Alice Blue",
	"Grayish Blue",
	"Slate Blue",
	"Dark Grayish Blue",
	"Blackish Blue",
	"Bluish White",
	"Light Bluish Gray",
	"Bluish Gray",
	"Dark Bluish Gray",
	"Bluish Black",
	"Vivid Purplish Blue",
	"Brilliant Purplish Blue",
	"Strong Purplish Blue",
	"Deep Purplish Blue",
	"Very Light Purplish Blue",
	"Light Purplish Blue",
	"Moderate Purplish Blue",
	"Dark Purplish Blue",
	"Very Pale Purplish Blue",
	"Pale Purplish Blue",
	"Grayish Purplish Blue",
	"Vivid Violet",
	"Brilliant Violet",
	"Strong Violet",
	"Deep Violet",
	"Very Light Violet",
	"Light Violet",
	"Moderate Violet",
	"Dark Violet",
	"Very Pale Violet",
	"Pale Violet",
	"Grayish Violet",
	"Vivid Purple",
	"Brilliant Purple",
	"Strong Purple",
	"Deep Purple",
	"Very Deep Purple",
	"Very Light Purple",
	"Light Purple",
	"Moderate Purple",
	"Dark Purple",
	"Very Dark Purple",
	"Very Pale Purple",
	"Pale Purple",
	"Grayish Purple",
	"Dark Grayish Purple",
	"Blackish Purple",
	"Purplish White",
	"Light Purplish Gray",
	"Purplish Gray",
	"Dark Purplish Gray",
	"Purplish Black",
	"Vivid Reddish Purple",
	"Strong Reddish Purple",
	"Deep Reddish Purple",
	"Very Deep Reddish Purple",
	"Light Reddish Purple",
	"Moderate Reddish Purple",
	"Dark Reddish Purple",
	"Very Dark Reddish Purple",
	"Pale Reddish Purple",
	"Grayish Reddish Purple",
	"Brilliant Purplish Pink",
	"Strong Purplish Pink",
	"Deep Purplish Pink",
	"Light Purplish Pink",
	"Moderate Purplish Pink",
	"Dark Purplish Pink",
	"Pale Purplish Pink",
	"Grayish Purplish Pink",
	"Vivid Purplish Red",
	"Strong Purplish Red",
	"Deep Purplish Red",
	"Very Deep Purplish Red",
	"Moderate Purplish Red",
	"Dark Purplish Red",
	"Very Dark Purplish Red",
	"Light Grayish Purplish Red",
	"Grayish Purplish Red",
	"White",
	"Light Gray",
	"Medium Gray",
	"Dark Gray",
	"Black",
];

// From https://catalog.lindahall.org/discovery/delivery/01LINDAHALL_INST:LHL/1284517120005961
pub const SACCARDO: [&str; 53] = [
	"Albus (white)",
	"Griseus (ash grey)",
	"Murinus (mouse grey)",
	"Ater (somber)",
	"Melænus (black)",
	"Fumosus (smoky)",
	"Avellaneus (hazel)",
	"Isabellinus (leather red)",
	"Umbrinus (umber)",
	"Castaneus (chestnut)",
	"Fuligineus (soot)",
	"Atropurpureus (dark purple)",
	"Purpureus (purple)",
	"Sanguineus (blood)",
	"Ruber (red)",
	"Miniatus (scarlet)",
	"Incarnatus (coral)",
	"Roseus (pink)",
	"Testaceus (terracota)",
	"Latericius (brick)",
	"Badius (bay)",
	"Aurantiacus (orange)",
	"Luteus (egg yolk)",
	"Flavus (yellow)",
	"Citrinus (lemon)",
	"Sulphureus (sulfur)",
	"Stramineus (straw)",
	"Cremeus (cream)",
	"Ochroleucus (yellow white)",
	"Ochraceus (ochre)",
	"Melleus (honey)",
	"Ferrugineus (rust)",
	"Fulvus (tawny)",
	"Flavo virens (yellow green)",
	"Atro virens (dark green)",
	"Viridis (green)",
	"Prasinus (smaragdine)",
	"Ærugineus (verdigris)",
	"Glaucus (sea green)",
	"Olivaceus (olive green)",
	"Atro cyaneus (prussian blue)",
	"Cyaneus (azure)",
	"Cæruleus (sky blue)",
	"Cæsius (eye blue)",
	"Plumbeus (lead)",
	"Ardesiacus (slate)",
	"Atro-violaceus (dark violet)",
	"Violaceus (violet)",
	"Lilacinus (lilac)",
	"Lividus (livid)",
	"Vinosus (wine)",
	"Achrous (colourless)",
	"Sordidus (dirty)",
];
