allow-branch = ["main"]
consolidate-pushes = true
push-options = ["--follow-tags"]
push-remote = "git@github.com:storily/fundere.git"

publish = false

[[pre-release-replacements]]
file = "CITATION.cff"
search = "^version: \"?[\\d.]+(-.+)?\"?"
replace = "version: \"{{version}}\""
prerelease = true
max = 1

[[pre-release-replacements]]
file = "CITATION.cff"
search = "^date-released: .+(-.+)?"
replace = "date-released: {{date}}"
prerelease = true
max = 1
